name: Build with caching & artifacts

on:
  push:
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Steup NodeJs
        uses: actions/setup-node@v6.5.0
        with:
          node-version: 24.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build
